sonar.organization=potapova13nastya-sketch
sonar.projectKey=potapova13nastya-sketch_coverage-demo
sonar.host.url=https://sonarcloud.io

# Пути к исходникам
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.libraries=target/dependency/*.jar

# Настройки покрытия
sonar.coverage.exclusions=**/*Test.java,**/test/**/*.java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports

# Quality Gate для нового кода
sonar.qualitygate.wait=true
sonar.newcoverage.required=70

# Исключения
sonar.exclusions=**/target/**,**/*.xml,**/*.yml,**/*.properties,**/scripts/**
sonar.test.exclusions=**/target/**

# Язык
sonar.language=java
sonar.java.source=17
sonar.java.target=17
